"""Save selected points also to DB

Revision ID: 0253d1131b84
Revises: 6a3a9188c17b
Create Date: 2024-07-15 17:10:24.814177

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0253d1131b84"
down_revision: Union[str, None] = "6a3a9188c17b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instrumentexperimentchannel",
        sa.Column(
            "baseline_chosen_points",
            sa.JSON(),
            nullable=True,
            server_default="[]",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instrumentexperimentchannel", "baseline_chosen_points")
    # ### end Alembic commands ###
