"""Add relationship between instrument experiment and project

Revision ID: 080c1302dd11
Revises: 95af72423de5
Create Date: 2024-07-17 16:29:55.807642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '080c1302dd11'
down_revision: Union[str, None] = '95af72423de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrumentexperiment', sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_instrumentexperiment_project_id'), 'instrumentexperiment', ['project_id'], unique=False)
    op.create_foreign_key(None, 'instrumentexperiment', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instrumentexperiment', type_='foreignkey')
    op.drop_index(op.f('ix_instrumentexperiment_project_id'), table_name='instrumentexperiment')
    op.drop_column('instrumentexperiment', 'project_id')
    # ### end Alembic commands ###
