"""Set name on create/update, not at read for profiles

Revision ID: 08fe22b0f490
Revises: c895caba6bd3
Create Date: 2024-05-08 17:01:39.078605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '08fe22b0f490'
down_revision: Union[str, None] = 'c895caba6bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soilprofile', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_soilprofile_name'), 'soilprofile', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soilprofile_name'), table_name='soilprofile')
    op.drop_column('soilprofile', 'name')
    # ### end Alembic commands ###
