"""Use enum for gradient

Revision ID: 128f1f044730
Revises: 8d7b02065942
Create Date: 2024-06-25 14:24:25.398053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '128f1f044730'
down_revision: Union[str, None] = '8d7b02065942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('flat', 'slope', name='gradientchoices').create(op.get_bind())
    op.alter_column('plot', 'gradient',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('flat', 'slope', name='gradientchoices'),
               existing_nullable=False,
               postgresql_using='gradient::gradientchoices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plot', 'gradient',
               existing_type=sa.Enum('flat', 'slope', name='gradientchoices'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    sa.Enum('flat', 'slope', name='gradientchoices').drop(op.get_bind())
    # ### end Alembic commands ###
