"""Set horizon description to JSON

Revision ID: 1675aa811f26
Revises: d1ab3ea26e63
Create Date: 2024-05-08 11:49:13.503552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1675aa811f26"
down_revision: Union[str, None] = "d1ab3ea26e63"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "soilprofile",
        "description_horizon",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        existing_nullable=True,
        postgresql_using="description_horizon::json",
    )
    op.alter_column(
        "soilprofile",
        "aspect",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "soilprofile",
        "aspect",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=True,
    )
    op.alter_column(
        "soilprofile",
        "description_horizon",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
