"""Add GNSS table

Revision ID: 307ac68ac38b
Revises: 8281b3073245
Create Date: 2024-06-26 16:47:19.851009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '307ac68ac38b'
down_revision: Union[str, None] = '8281b3073245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gnss',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('file', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_gnss_id'), 'gnss', ['id'], unique=False)
    op.create_index(op.f('ix_gnss_iterator'), 'gnss', ['iterator'], unique=False)
    op.create_index(op.f('ix_gnss_name'), 'gnss', ['name'], unique=False)
    op.alter_column('plotsample', 'sample_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('plotsample', 'subsample_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plotsample', 'subsample_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('plotsample', 'sample_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_gnss_name'), table_name='gnss')
    op.drop_index(op.f('ix_gnss_iterator'), table_name='gnss')
    op.drop_index(op.f('ix_gnss_id'), table_name='gnss')
    op.drop_table('gnss')
    # ### end Alembic commands ###
