"""Update plot fields

Revision ID: 346f9c6d0589
Revises: 23a5f1db56c3
Create Date: 2024-05-06 10:13:21.820534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '346f9c6d0589'
down_revision: Union[str, None] = '23a5f1db56c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('vegetation_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('plot', sa.Column('topography', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('plot', sa.Column('aspect', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('plot', sa.Column('created_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plot', 'created_on')
    op.drop_column('plot', 'aspect')
    op.drop_column('plot', 'topography')
    op.drop_column('plot', 'vegetation_type')
    # ### end Alembic commands ###
