"""Add average column

Revision ID: 376634bd3252
Revises: 982e7db5bedc
Create Date: 2024-09-03 16:31:50.189750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '376634bd3252'
down_revision: Union[str, None] = '982e7db5bedc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('temperature_average', sa.Float(), nullable=True))
    op.create_index(op.f('ix_sensordata_temperature_average'), 'sensordata', ['temperature_average'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sensordata_temperature_average'), table_name='sensordata')
    op.drop_column('sensordata', 'temperature_average')
    # ### end Alembic commands ###
