"""Add ts vector on plot table

Revision ID: 423836342799
Revises: f2dee975866b
Create Date: 2024-07-16 17:27:51.816432

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = "423836342799"
down_revision: Union[str, None] = "f2dee975866b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "plot",
        sa.Column(
            "tsvector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            sa.Computed(
                "to_tsvector('english', name) || to_tsvector('english', COALESCE(vegetation_type, '')) || to_tsvector('english', COALESCE(topography, '')) || to_tsvector('english', COALESCE(aspect, '')) || to_tsvector('english', COALESCE(weather, '')) || to_tsvector('english', COALESCE(lithology, ''))",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_plot_tsvector",
        "plot",
        ["tsvector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_plot_tsvector", table_name="plot", postgresql_using="gin"
    )
    op.drop_column("plot", "tsvector")
    # ### end Alembic commands ###
