"""Add soil type relationship

Revision ID: 42d41676cb22
Revises: 72a186e68ea8
Create Date: 2024-05-06 11:39:46.032819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42d41676cb22'
down_revision: Union[str, None] = '72a186e68ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('soil_type_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.create_index(op.f('ix_plot_soil_type_id'), 'plot', ['soil_type_id'], unique=False)
    op.create_foreign_key(None, 'plot', 'soiltype', ['soil_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plot', type_='foreignkey')
    op.drop_index(op.f('ix_plot_soil_type_id'), table_name='plot')
    op.drop_column('plot', 'soil_type_id')
    # ### end Alembic commands ###
