"""Add image to plot

Revision ID: 50efd46a2b7b
Revises: cce16b65229f
Create Date: 2024-06-07 11:21:11.716946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '50efd46a2b7b'
down_revision: Union[str, None] = 'cce16b65229f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('hlallgmein_zusammenfassung_merged_shape_geom_idx', table_name='hlallgmein_zusammenfassung_merged', postgresql_using='gist', column_name='shape')
    op.drop_geospatial_table('hlallgmein_zusammenfassung_merged')
    op.add_column('plot', sa.Column('image', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plot', 'image')
    op.create_geospatial_table('hlallgmein_zusammenfassung_merged',
    sa.Column('objectid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('gridcode', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lknr', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('aenderungsdatum', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('hl_klasse', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('hl_neigung_hang', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('shape_length', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shape_area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shape', Geometry(geometry_type='MULTIPOLYGON', srid=2056, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('objectid', name='hlallgmein_zusammenfassung_merged_pkey')
    )
    op.create_geospatial_index('hlallgmein_zusammenfassung_merged_shape_geom_idx', 'hlallgmein_zusammenfassung_merged', ['shape'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###
