"""Change name to plot iterator numeric

Revision ID: 5e1938c8cfbe
Revises: 346f9c6d0589
Create Date: 2024-05-06 10:24:03.368492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e1938c8cfbe'
down_revision: Union[str, None] = '346f9c6d0589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('plot_iterator', sa.Integer(), nullable=False))
    op.drop_index('ix_plot_name', table_name='plot')
    op.create_index(op.f('ix_plot_plot_iterator'), 'plot', ['plot_iterator'], unique=False)
    op.create_unique_constraint('unique_plot', 'plot', ['plot_iterator', 'area_id', 'gradient'])
    op.drop_column('plot', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('unique_plot', 'plot', type_='unique')
    op.drop_index(op.f('ix_plot_plot_iterator'), table_name='plot')
    op.create_index('ix_plot_name', 'plot', ['name'], unique=False)
    op.drop_column('plot', 'plot_iterator')
    # ### end Alembic commands ###
