"""Remove data table for instruments and store in channels instead

Revision ID: 6a3a9188c17b
Revises: 77e43ef171a5
Create Date: 2024-07-12 16:37:40.103898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a3a9188c17b'
down_revision: Union[str, None] = '77e43ef171a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_instrumentexperimentdata_id', table_name='instrumentexperimentdata')
    op.drop_index('ix_instrumentexperimentdata_iterator', table_name='instrumentexperimentdata')
    op.drop_table('instrumentexperimentdata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrumentexperimentdata',
    sa.Column('experiment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('baseline_corrected', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('iterator', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['instrumentexperimentchannel.id'], name='instrumentexperimentdata_channel_id_fkey'),
    sa.ForeignKeyConstraint(['experiment_id'], ['instrumentexperiment.id'], name='instrumentexperimentdata_experiment_id_fkey'),
    sa.PrimaryKeyConstraint('iterator', name='instrumentexperimentdata_pkey'),
    sa.UniqueConstraint('id', name='instrumentexperimentdata_id_key')
    )
    op.create_index('ix_instrumentexperimentdata_iterator', 'instrumentexperimentdata', ['iterator'], unique=False)
    op.create_index('ix_instrumentexperimentdata_id', 'instrumentexperimentdata', ['id'], unique=False)
    # ### end Alembic commands ###
