"""Add slope

Revision ID: 72a186e68ea8
Revises: 5e1938c8cfbe
Create Date: 2024-05-06 11:29:43.350370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '72a186e68ea8'
down_revision: Union[str, None] = '5e1938c8cfbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('slope', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plot', 'slope')
    # ### end Alembic commands ###
