"""Add project_id foreign key to areas

Revision ID: 77f95220072c
Revises: 6a229995ab5d
Create Date: 2024-05-03 16:11:44.534309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '77f95220072c'
down_revision: Union[str, None] = '6a229995ab5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_index(op.f('ix_area_project_id'), 'area', ['project_id'], unique=False)
    op.create_foreign_key(None, 'area', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'area', type_='foreignkey')
    op.drop_index(op.f('ix_area_project_id'), table_name='area')
    op.drop_column('area', 'project_id')
    # ### end Alembic commands ###
