"""Add instrument tables

Revision ID: 812bfec68907
Revises: 9d2293bce607
Create Date: 2024-07-11 12:00:44.824617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '812bfec68907'
down_revision: Union[str, None] = '9d2293bce607'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrumentexperiment',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instrument_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('init_e', sa.Float(), nullable=True),
    sa.Column('sample_interval', sa.Float(), nullable=True),
    sa.Column('run_time', sa.Float(), nullable=True),
    sa.Column('quiet_time', sa.Float(), nullable=True),
    sa.Column('sensitivity', sa.Float(), nullable=True),
    sa.Column('samples', sa.Integer(), nullable=True),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_instrumentexperiment_id'), 'instrumentexperiment', ['id'], unique=False)
    op.create_index(op.f('ix_instrumentexperiment_iterator'), 'instrumentexperiment', ['iterator'], unique=False)
    op.create_index(op.f('ix_instrumentexperiment_name'), 'instrumentexperiment', ['name'], unique=False)
    op.create_table('instrumentexperimentchannel',
    sa.Column('channel_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experiment_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('spline', sa.JSON(), nullable=True),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['instrumentexperiment.id'], ),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_instrumentexperimentchannel_id'), 'instrumentexperimentchannel', ['id'], unique=False)
    op.create_index(op.f('ix_instrumentexperimentchannel_iterator'), 'instrumentexperimentchannel', ['iterator'], unique=False)
    op.create_table('instrumentexperimentdata',
    sa.Column('experiment_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('channel_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('time', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('baseline_corrected', sa.Boolean(), nullable=False),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['instrumentexperimentchannel.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['instrumentexperiment.id'], ),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_instrumentexperimentdata_id'), 'instrumentexperimentdata', ['id'], unique=False)
    op.create_index(op.f('ix_instrumentexperimentdata_iterator'), 'instrumentexperimentdata', ['iterator'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_instrumentexperimentdata_iterator'), table_name='instrumentexperimentdata')
    op.drop_index(op.f('ix_instrumentexperimentdata_id'), table_name='instrumentexperimentdata')
    op.drop_table('instrumentexperimentdata')
    op.drop_index(op.f('ix_instrumentexperimentchannel_iterator'), table_name='instrumentexperimentchannel')
    op.drop_index(op.f('ix_instrumentexperimentchannel_id'), table_name='instrumentexperimentchannel')
    op.drop_table('instrumentexperimentchannel')
    op.drop_index(op.f('ix_instrumentexperiment_name'), table_name='instrumentexperiment')
    op.drop_index(op.f('ix_instrumentexperiment_iterator'), table_name='instrumentexperiment')
    op.drop_index(op.f('ix_instrumentexperiment_id'), table_name='instrumentexperiment')
    op.drop_table('instrumentexperiment')
    # ### end Alembic commands ###
