"""Add microbial fields to samples

Revision ID: 8281b3073245
Revises: 901e82409c49
Create Date: 2024-06-26 11:49:23.605066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8281b3073245'
down_revision: Union[str, None] = '901e82409c49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plotsample', sa.Column('fungi_per_g', sa.Float(), nullable=True))
    op.add_column('plotsample', sa.Column('bacteria_per_g', sa.Float(), nullable=True))
    op.add_column('plotsample', sa.Column('archea_per_g', sa.Float(), nullable=True))
    op.add_column('plotsample', sa.Column('methanogens_per_g', sa.Float(), nullable=True))
    op.add_column('plotsample', sa.Column('methanotrophs_per_g', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plotsample', 'methanotrophs_per_g')
    op.drop_column('plotsample', 'methanogens_per_g')
    op.drop_column('plotsample', 'archea_per_g')
    op.drop_column('plotsample', 'bacteria_per_g')
    op.drop_column('plotsample', 'fungi_per_g')
    # ### end Alembic commands ###
