"""Remove autogenerated name

Revision ID: 88e8f91ea9e9
Revises: b6b514733b67
Create Date: 2024-07-25 17:12:58.781371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88e8f91ea9e9'
down_revision: Union[str, None] = 'b6b514733b67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
