"""Create plot table

Revision ID: 8bcd36b53baf
Revises: adbd9f38a773
Create Date: 2024-04-15 15:40:37.195087

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8bcd36b53baf"
down_revision: Union[str, None] = "adbd9f38a773"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table(
        "plot",
        sa.Column("iterator", sa.Integer(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.GUID(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "description_horizon",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="POINTZ",
                srid=2056,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("iterator"),
        sa.UniqueConstraint("id"),
    )
    op.create_geospatial_index(
        "idx_plot_geom",
        "plot",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(op.f("ix_plot_id"), "plot", ["id"], unique=False)
    op.create_index(
        op.f("ix_plot_iterator"), "plot", ["iterator"], unique=False
    )
    op.create_index(op.f("ix_plot_name"), "plot", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_plot_name"), table_name="plot")
    op.drop_index(op.f("ix_plot_iterator"), table_name="plot")
    op.drop_index(op.f("ix_plot_id"), table_name="plot")
    op.drop_geospatial_index(
        "idx_plot_geom",
        table_name="plot",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("plot")
    # ### end Alembic commands ###
