"""Avoid storing file, use fields extracted from XML instead

Revision ID: 8d125bb161c5
Revises: 307ac68ac38b
Create Date: 2024-06-26 16:59:43.912179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d125bb161c5'
down_revision: Union[str, None] = '307ac68ac38b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gnss', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('gnss', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('gnss', sa.Column('elevation', sa.Float(), nullable=False))
    op.add_column('gnss', sa.Column('time', sa.DateTime(), nullable=False))
    op.add_column('gnss', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('gnss', sa.Column('depth', sa.Float(), nullable=True))
    op.add_column('gnss', sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('gnss', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_gnss_name', table_name='gnss')
    op.drop_column('gnss', 'file')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gnss', sa.Column('file', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_gnss_name', 'gnss', ['name'], unique=False)
    op.alter_column('gnss', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('gnss', 'original_filename')
    op.drop_column('gnss', 'depth')
    op.drop_column('gnss', 'comment')
    op.drop_column('gnss', 'time')
    op.drop_column('gnss', 'elevation')
    op.drop_column('gnss', 'longitude')
    op.drop_column('gnss', 'latitude')
    # ### end Alembic commands ###
