"""Add transect and node relationship tables

Revision ID: 8d7b02065942
Revises: fac597801e87
Create Date: 2024-06-13 10:31:14.003959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d7b02065942'
down_revision: Union[str, None] = 'fac597801e87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transect',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_transect_date_created'), 'transect', ['date_created'], unique=False)
    op.create_index(op.f('ix_transect_id'), 'transect', ['id'], unique=False)
    op.create_index(op.f('ix_transect_iterator'), 'transect', ['iterator'], unique=False)
    op.create_index(op.f('ix_transect_name'), 'transect', ['name'], unique=False)
    op.create_table('transectnode',
    sa.Column('plot_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('transect_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], ),
    sa.ForeignKeyConstraint(['transect_id'], ['transect.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order', 'transect_id', name='no_same_order_constraint'),
    sa.UniqueConstraint('transect_id', 'plot_id', name='no_same_link_constraint')
    )
    op.create_index(op.f('ix_transectnode_id'), 'transectnode', ['id'], unique=False)
    op.create_index(op.f('ix_transectnode_plot_id'), 'transectnode', ['plot_id'], unique=False)
    op.create_index(op.f('ix_transectnode_transect_id'), 'transectnode', ['transect_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transectnode_transect_id'), table_name='transectnode')
    op.drop_index(op.f('ix_transectnode_plot_id'), table_name='transectnode')
    op.drop_index(op.f('ix_transectnode_id'), table_name='transectnode')
    op.drop_table('transectnode')
    op.drop_index(op.f('ix_transect_name'), table_name='transect')
    op.drop_index(op.f('ix_transect_iterator'), table_name='transect')
    op.drop_index(op.f('ix_transect_id'), table_name='transect')
    op.drop_index(op.f('ix_transect_date_created'), table_name='transect')
    op.drop_table('transect')
    # ### end Alembic commands ###
