"""Add tsvector to area

Revision ID: 8f710f99643a
Revises: b1d731e141ba
Create Date: 2024-07-17 09:11:56.300276

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = "8f710f99643a"
down_revision: Union[str, None] = "b1d731e141ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "area",
        sa.Column(
            "tsvector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            sa.Computed(
                "to_tsvector('english', name) || to_tsvector('english', COALESCE(description, ''))",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_area_tsvector",
        "area",
        ["tsvector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_area_tsvector", table_name="area", postgresql_using="gin"
    )
    op.drop_column("area", "tsvector")
    # ### end Alembic commands ###
