"""Remove tsvector

Revision ID: 95af72423de5
Revises: 8f710f99643a
Create Date: 2024-07-17 09:27:26.963412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95af72423de5'
down_revision: Union[str, None] = '8f710f99643a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_area_tsvector', table_name='area', postgresql_using='gin')
    op.drop_column('area', 'tsvector')
    op.drop_index('ix_plot_tsvector', table_name='plot', postgresql_using='gin')
    op.drop_column('plot', 'tsvector')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('tsvector', postgresql.TSVECTOR(), sa.Computed("(((((to_tsvector('english'::regconfig, (name)::text) || to_tsvector('english'::regconfig, (COALESCE(vegetation_type, ''::character varying))::text)) || to_tsvector('english'::regconfig, (COALESCE(topography, ''::character varying))::text)) || to_tsvector('english'::regconfig, (COALESCE(aspect, ''::character varying))::text)) || to_tsvector('english'::regconfig, (COALESCE(weather, ''::character varying))::text)) || to_tsvector('english'::regconfig, (COALESCE(lithology, ''::character varying))::text))", persisted=True), autoincrement=False, nullable=True))
    op.create_index('ix_plot_tsvector', 'plot', ['tsvector'], unique=False, postgresql_using='gin')
    op.add_column('area', sa.Column('tsvector', postgresql.TSVECTOR(), sa.Computed("(to_tsvector('english'::regconfig, (name)::text) || to_tsvector('english'::regconfig, (COALESCE(description, ''::character varying))::text))", persisted=True), autoincrement=False, nullable=True))
    op.create_index('ix_area_tsvector', 'area', ['tsvector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
