"""Add plot sample table

Revision ID: 9bb039b52215
Revises: a0e71a0fd9e3
Create Date: 2024-05-08 14:17:54.803393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9bb039b52215'
down_revision: Union[str, None] = 'a0e71a0fd9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plotsample',
    sa.Column('name', sa.Enum('A', 'B', 'C', name='plotsamplenames'), nullable=False),
    sa.Column('upper_depth_cm', sa.Float(), nullable=False),
    sa.Column('lower_depth_cm', sa.Float(), nullable=False),
    sa.Column('plot_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('sample_weight', sa.Float(), nullable=False),
    sa.Column('subsample_weight', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ph', sa.Float(), nullable=True),
    sa.Column('rh', sa.Float(), nullable=True),
    sa.Column('loi', sa.Float(), nullable=True),
    sa.Column('mfc', sa.Float(), nullable=True),
    sa.Column('c', sa.Float(), nullable=True),
    sa.Column('n', sa.Float(), nullable=True),
    sa.Column('cn', sa.Float(), nullable=True),
    sa.Column('clay_percent', sa.Float(), nullable=True),
    sa.Column('silt_percent', sa.Float(), nullable=True),
    sa.Column('sand_percent', sa.Float(), nullable=True),
    sa.Column('fe_ug_per_g', sa.Integer(), nullable=True),
    sa.Column('al_ug_per_g', sa.Integer(), nullable=True),
    sa.Column('k_ug_per_g', sa.Integer(), nullable=True),
    sa.Column('ca_ug_per_g', sa.Integer(), nullable=True),
    sa.Column('mg_ug_per_g', sa.Integer(), nullable=True),
    sa.Column('mn_ug_per_g', sa.Float(), nullable=True),
    sa.Column('s_ug_per_g', sa.Float(), nullable=True),
    sa.Column('cl_ug_per_g', sa.Float(), nullable=True),
    sa.Column('p_ug_per_g', sa.Float(), nullable=True),
    sa.Column('si_ug_per_g', sa.Float(), nullable=True),
    sa.Column('iterator', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plot.id'], ),
    sa.PrimaryKeyConstraint('iterator'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_plotsample_id'), 'plotsample', ['id'], unique=False)
    op.create_index(op.f('ix_plotsample_iterator'), 'plotsample', ['iterator'], unique=False)
    op.create_index(op.f('ix_plotsample_name'), 'plotsample', ['name'], unique=False)
    op.create_index(op.f('ix_plotsample_plot_id'), 'plotsample', ['plot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plotsample_plot_id'), table_name='plotsample')
    op.drop_index(op.f('ix_plotsample_name'), table_name='plotsample')
    op.drop_index(op.f('ix_plotsample_iterator'), table_name='plotsample')
    op.drop_index(op.f('ix_plotsample_id'), table_name='plotsample')
    op.drop_table('plotsample')
    # ### end Alembic commands ###
