"""Add area relation to transect

Revision ID: 9d2293bce607
Revises: 89dbfeab7ba7
Create Date: 2024-06-29 15:32:54.234367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d2293bce607'
down_revision: Union[str, None] = '89dbfeab7ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transect', sa.Column('area_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_index(op.f('ix_transect_area_id'), 'transect', ['area_id'], unique=False)
    op.create_foreign_key(None, 'transect', 'area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transect', type_='foreignkey')
    op.drop_index(op.f('ix_transect_area_id'), table_name='transect')
    op.drop_column('transect', 'area_id')
    # ### end Alembic commands ###
