"""Fix date name for consistency

Revision ID: a0e71a0fd9e3
Revises: 86a0eb669677
Create Date: 2024-05-08 13:28:20.956201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0e71a0fd9e3'
down_revision: Union[str, None] = '86a0eb669677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plot', 'description_horizon')
    op.add_column('soilprofile', sa.Column('created_on', sa.DateTime(), nullable=True))
    op.drop_index('ix_soilprofile_date_created', table_name='soilprofile')
    op.create_index(op.f('ix_soilprofile_created_on'), 'soilprofile', ['created_on'], unique=False)
    op.drop_column('soilprofile', 'date_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soilprofile', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_soilprofile_created_on'), table_name='soilprofile')
    op.create_index('ix_soilprofile_date_created', 'soilprofile', ['date_created'], unique=False)
    op.drop_column('soilprofile', 'created_on')
    op.add_column('plot', sa.Column('description_horizon', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
