"""Modify nullable constraint

Revision ID: a97c8797c196
Revises: 812bfec68907
Create Date: 2024-07-11 13:33:33.331341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a97c8797c196'
down_revision: Union[str, None] = '812bfec68907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instrumentexperiment', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('instrumentexperiment', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instrumentexperiment', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('instrumentexperiment', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
