"""Add subsample replica weight, modify non-nullable subsample

Revision ID: ae31aa270f11
Revises: 2ac3352169b4
Create Date: 2024-05-15 10:28:38.604807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ae31aa270f11'
down_revision: Union[str, None] = '2ac3352169b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plotsample', sa.Column('subsample_replica_weight', sa.Float(), nullable=True))
    op.alter_column('plotsample', 'subsample_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plotsample', 'subsample_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('plotsample', 'subsample_replica_weight')
    # ### end Alembic commands ###
