"""Set integers to floats in samples

Revision ID: bc44c27c7829
Revises: 08fe22b0f490
Create Date: 2024-05-08 17:08:12.582221

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "bc44c27c7829"
down_revision: Union[str, None] = "08fe22b0f490"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plotsample",
        "subsample_weight",
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="subsample_weight::float",
    )
    op.alter_column(
        "plotsample",
        "fe_ug_per_g",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="fe_ug_per_g::float",
    )
    op.alter_column(
        "plotsample",
        "al_ug_per_g",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="al_ug_per_g::float",
    )
    op.alter_column(
        "plotsample",
        "k_ug_per_g",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="k_ug_per_g::float",
    )
    op.alter_column(
        "plotsample",
        "ca_ug_per_g",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="ca_ug_per_g::float",
    )
    op.alter_column(
        "plotsample",
        "mg_ug_per_g",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="mg_ug_per_g::float",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plotsample",
        "mg_ug_per_g",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "plotsample",
        "ca_ug_per_g",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "plotsample",
        "k_ug_per_g",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "plotsample",
        "al_ug_per_g",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "plotsample",
        "fe_ug_per_g",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=True,
    )
    op.alter_column(
        "plotsample",
        "subsample_weight",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
