"""Add points to channel information, change name of spline

Revision ID: c5245bffc72f
Revises: 53976e3abbd6
Create Date: 2024-07-12 11:25:09.659847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5245bffc72f'
down_revision: Union[str, None] = '53976e3abbd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrumentexperimentchannel', sa.Column('baseline_spline', sa.JSON(), nullable=True))
    op.add_column('instrumentexperimentchannel', sa.Column('baseline_points', sa.JSON(), nullable=True))
    op.drop_column('instrumentexperimentchannel', 'spline')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrumentexperimentchannel', sa.Column('spline', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('instrumentexperimentchannel', 'baseline_points')
    op.drop_column('instrumentexperimentchannel', 'baseline_spline')
    # ### end Alembic commands ###
