"""Set name on create/update, not at read

Revision ID: c895caba6bd3
Revises: 9bb039b52215
Create Date: 2024-05-08 16:33:41.062875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c895caba6bd3'
down_revision: Union[str, None] = '9bb039b52215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plot', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_plot_name'), 'plot', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plot_name'), table_name='plot')
    op.drop_column('plot', 'name')
    # ### end Alembic commands ###
