"""Add area to soil profiles

Revision ID: d1ab3ea26e63
Revises: 0e2339ff8f28
Create Date: 2024-05-08 10:37:21.102077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd1ab3ea26e63'
down_revision: Union[str, None] = '0e2339ff8f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soilprofile', sa.Column('area_id', sqlmodel.sql.sqltypes.GUID(), nullable=False))
    op.create_index(op.f('ix_soilprofile_area_id'), 'soilprofile', ['area_id'], unique=False)
    op.create_foreign_key(None, 'soilprofile', 'area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'soilprofile', type_='foreignkey')
    op.drop_index(op.f('ix_soilprofile_area_id'), table_name='soilprofile')
    op.drop_column('soilprofile', 'area_id')
    # ### end Alembic commands ###
