"""Use server update on model

Revision ID: d3aea07bba7d
Revises: 182698c00e97
Create Date: 2024-05-15 12:08:33.346863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd3aea07bba7d'
down_revision: Union[str, None] = '182698c00e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensordata', sa.Column('last_updated', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensordata', 'last_updated')
    # ### end Alembic commands ###
