"""Modify fields in gnss table

Revision ID: d972e30810fc
Revises: 8d125bb161c5
Create Date: 2024-06-26 17:43:37.521962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd972e30810fc'
down_revision: Union[str, None] = '8d125bb161c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gnss', sa.Column('elevation_gps', sa.Float(), nullable=False))
    op.add_column('gnss', sa.Column('elevation_corrected', sa.Float(), nullable=True))
    op.drop_column('gnss', 'elevation')
    op.drop_column('gnss', 'depth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gnss', sa.Column('depth', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('gnss', sa.Column('elevation', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('gnss', 'elevation_corrected')
    op.drop_column('gnss', 'elevation_gps')
    # ### end Alembic commands ###
