"""Remove slope, add parent material

Revision ID: dcb761fb9b0f
Revises: 3c3962a873e0
Create Date: 2024-06-28 14:17:31.294902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dcb761fb9b0f'
down_revision: Union[str, None] = '3c3962a873e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plot', 'slope')
    op.add_column('soilprofile', sa.Column('parent_material', sa.Float(), nullable=True))
    op.drop_column('soilprofile', 'slope')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soilprofile', sa.Column('slope', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('soilprofile', 'parent_material')
    op.add_column('plot', sa.Column('slope', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
