"""Add integral fields

Revision ID: f2dee975866b
Revises: 0253d1131b84
Create Date: 2024-07-16 13:59:35.433195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "f2dee975866b"
down_revision: Union[str, None] = "0253d1131b84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instrumentexperimentchannel",
        sa.Column(
            "integral_chosen_pairs",
            sa.JSON(),
            nullable=True,
            server_default="[]",
        ),
    )
    op.add_column(
        "instrumentexperimentchannel",
        sa.Column(
            "integral_results", sa.JSON(), nullable=True, server_default="[]"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instrumentexperimentchannel", "integral_results")
    op.drop_column("instrumentexperimentchannel", "integral_chosen_pairs")
    # ### end Alembic commands ###
