"""Add images to soil profiles

Revision ID: fac597801e87
Revises: 440bd243c866
Create Date: 2024-06-07 15:52:13.881615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fac597801e87'
down_revision: Union[str, None] = '440bd243c866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soilprofile', sa.Column('soil_diagram', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('soilprofile', sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soilprofile', 'photo')
    op.drop_column('soilprofile', 'soil_diagram')
    # ### end Alembic commands ###
